layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# projects:
#   sort_by: stars
#   # sort_by options:
#   #   - pushed
#   #   - stars
#   limit: 3
#   exclude:
#     archived: false
#     forks: true
#     projects: "Price_Of_Anarchy"
#     # - repo-name

social_media:
  # behance: your_username
  email: "rupal004phd23@igdtuw.ac.in"
  telegram: RupalJain15081
  github: jnoni
  twitter: rupal15081
  linkedin: rupal-jain-677301125
  discord: 710743860913111041
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: sahana-ramnath
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: sahana_ramnath
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

papers:
  - name: "Ukraine Math and Science Achievement Fund"
    web_url: https://ukraineachievementfund.org/
    authors: Mentor and Program Advisor
    location: I am helping high school students who had to flee Ukraine post the Russian invasion find educational opportunities and funding in their new country of refuge, new school, and get selected for top CS programs in the West. Some of my mentees recently got acceptances from University of Cambridge, British Columbia, University of Toronto. Currently helping their organisers to restructure the program to achieve better results and build a stronger community.

  - name: "Rewriting the Code (RTC)"
    web_url: https://rewritingthecode.org/
    authors: Advisory Board Member, Mentor, Educator
    location: Community of 14,000+ exceptional career women who are thriving engineers and tech leaders. They come from 800+ universities, 81 countries. I helped create strategy and identify focal points for the RTC international community outreach. Together, I raised scholarships to assist my mentees with their educational expenses, managed to get community scholarships from Google, Anita Borg organization. I assisted our digital libraries to be rich with beautiful, expansive narratives. It has been >3 years since I have been actively tutoring, mentoring >100 RTC women to groom their profiles and hone skills to get their dream jobs in big tech, hosting workshops, organizing celebrations for community members who didn’t have a family to return to during holidays, advocating for one another, helping my mentees secure offers from topmost international finance and tech firms, help them strategize and negotiate salary jumps from $40,000 to upward of $100,000, standing up against toxic gender norms and much more.

  - name: "National Campaign on Dalit Human Rights"
    web_url: https://jnoni.github.io/2016/08/01/Community-Service/
    authors: Program Manager and Community Builder, Economic Rights Team
    location: Led the LunchnLearn program at the NCDHR, an NGO eradicating caste-based discrimination against Dalits. Convince 25 families to enroll their girl child into our program. Taught English, Finance, Mathematics, CS, soft skills, general hygiene.

  - name: "Helping Hands NGO - Govt. Of India"
    authors: School Teacher
    location: Taught at RPVV Lajpat Nagar, mentored students from underprivileged backgrounds, helped build foundations in Maths-Science, explore beyond classroom curriculum. Volunteered for the Project Roshni to gather, manage, redistribute funds and scholarships and donate books to underprivileged students.

  - name: "Indraprastha Institute of Information Technology, Delhi"
    web_url: https://iiitd.ac.in/
    authors: Academic Mentor and Community Counsellor
    location: Helped students make the most of their undergrad program, get the right research opportunities, graded papers, conducted repeat tutorials, offered office hours, assisted student-led projects, helped streamline the course structure to improve student learning. Coordinated summer course logistics, project infrastructure, and culture. Taught to design, analyze, and critique applications of data structures and algorithms in the areas of science, politics, and justice.

  - name: "Women in Tech IIITD"
    web_url: https://www.linkedin.com/company/witiiitd/about/
    authors: Community Director, Opportunity Lead, Mentor
    location: Spearheaded the campus community, telling women’s stories to the world, mentoring one-on-one. I rose the community to >5k members from universities PAN India. Invested in belief capital, resources, interview prep for collegiate women, profile polishing, interview grooming.

  - name: "Enactus IIITD"
    web_url: https://www.linkedin.com/company/enactus-iiitd/?originalSubdomain=in
    authors: Women Empowerment Cell Manager, Partnerships and New Initiatives
    location: It’s a leadership platform that enables sustainable development through Technology and Innovation. Managed their campaign that advocates right to accessible education for a girlchild. I was a counsellor and lead for the Violence Against Women branch of Enactus IIITD.

  - name: "Girl Up, United Nations Foundation"
    web_url: https://girlup.org/
    authors: Mentor and Advisor to the co-founders, IIITD Chapter
    location: A movement to advance girls’ skills, rights, opportunities to be leaders. I work on bringing right ideas into implementation, mentor the all-female founding team to lead community effectively, bringing awareness and relevant opportunities to collegiate women.

  - name: "The Coding School"
    web_url: https://the-cs.org/
    authors: Teaching Assistant and Curriculum Author
    location: Volunteered for The Coding School, national 501c3 nonprofit, preparing and enhancing modules for learning programming concepts, held coding and mentorship sessions for underrepresented middle and high school students who are differently-abled, to learn how to code.

  - name: "Lean In IIITD"
    web_url: https://leanin.org/
    authors: Community Mentor and Tutor
    location: A global community dedicated to helping women achieve their ambitions. I led their mentorship program, planning what the program should practically achieve. Understanding market space to bring relevant opportunities for women.

  - name: "Testimonials from some of my amazing mentees"
    authors: Coming Soon!
    location: 
    
misc:
  
  - name: "The False Truths - Time to Restore History"
    web_url: https://drive.google.com/file/d/1SD1TEj04njburP_FSSekc9xZhmmfpLX_/view
    authors: There can be no reconciliation and healing without being honest about the past. 
    location: How Colonial Opressors and Allied Powers most literally rewrote and whitewashed history, leaving the future generations disoriented and uprooted. Drawing inspiration from Faiz Ahmed Faiz’s iconic poem ‘Hum Dekhenge’, I call out the oppressors of every age, ideology and society. I cover themes such as religious segregation, India's colonial struggle, the history of genocide behind America's famous holidays, Churchill and his war crimes, and much more.

  - name: "The Ethics Of Whistleblowing"
    web_url: https://drive.google.com/file/d/1oI-R5bq8m_8nO-6IR2CQnXyC1Ywgng25/view
    authors: The ethical dilemma of conflicting loyalties and a conflict between personal and organisational values.
    location: For this response paper, we looked at the Peter Jubb’s paper titled 'Whistleblowing: A Restrictive Definition and Interpretation' published in Springer 1999. It discusses about - what are the different (often overlooked) aspects of whistleblowing and why it is essential to have an ethical focus on it.

  - name: "Animal Rights"
    web_url: https://drive.google.com/file/d/1i7o5guawO0TTWgKLzC41wGnc7mezoBaU/view
    authors: "Indifference is more dangerous than anger and hatred" - Elie Wiesel, a Noble laureate.
    location: Our indifference to an animal’s pain, a being that is habituated different from us, says an awful lot about our species. The movement for animal liberation is an ask for extending our most basic human decency to animals. In his 1975 account, Animal Liberation: A New Ethics for Our Treatment of Animals, Singer makes an appeal against speciesism, thus marking a historic shift in our perception of morality and its boundaries that too often fail to expand beyond homo sapiens, the 'cognitively superior' being. This founding philosophical work by Peter Singer put the discourse on animal ethics on the global map.
  
  - name: "Fundamental Human Rights vs National Prosperity"
    web_url: https://drive.google.com/file/d/14V0sca_PEEXoYyCQR4Le2W0fTMFA1kmw/view
    authors: Co-authored with with Jayant Malik, Mrinal, Prabhat Soni, and Pratyusha Lakshmi.
    location: Some of the themes that we covered are Ethics of Migration, Propagandized Education or Indoctrination, Data Privacy, Sedition Act of 1918, and Development-Induced Displacement.
  
  - name: "A leap of Career"
    authors: Coming Soon!
    location: Things to take care of while considering making career switches, evaluating options, finding the right support system, finding the person-door to that new field, all while leveraging the previous career. Some learnings from the two coveted fellowships I received (UNESCO and Stanford) both of which are poles apart and how I tried to interdiscipline the two.

  - name: "Big-Tech job interviewing 101 - Deflating that Hype"
    authors: Coming Soon!
    location: 

  - name: "My experience with Mercatus Center's Doctoral Fellowship"
    web_url: https://www.mercatus.org/
    authors: Coming Soon!
    location: 

  - name: "The Great War"
    web_url: https://open.spotify.com/track/3UMrglJeju5yWyYIW6o99b
    authors: Coming Soon!
    location: (But seriously, this is not about Taylor Swift's all-time-record-breaking Grammy-winning deeply vulnerable and personal album "Midnights". This article will actually be about Israel war and Palestine's struggle for Independence, the privilege reality-check it became for the rest of us, and the lessons that historical blunders can teach us about future. Because, Karma is sweet like justice.)

  - name: "How to be self-dependent as an Indian student - The Gig Game"
    authors: Coming Soon!
    location: 

  - name: "Taylor's Tale - Anatomy of her most underrated poems"
    authors: Coming Soon!
    location: 

  - name: "Building an education and allyship community ground-up"
    authors: Coming Soon!
    location: 

  - name: "My approach to writing research and scholarship proposals"
    authors: Bonus - How to find your career sponsor
    location: Coming Soon!

  - name: "Scholarship, Fellowship, Referral Database"
    authors: Coming Soon!
    location: Digging from my years of archival documents and reserves. If I get time, I might put them in an AirTable for easy filtering and scheduling.

  - name: "RTC and I"
    authors: Coming Soon!
    location: How RTC rewrote my career-code for real, how its people uplifted me, some even becoming my closest friends. Some lessons from last 6 years of RTC'ing and build a global network.

  - name: "Ditching Leetcode"
    authors: Coming Soon! 
    location: How to prepare for tech interviews old-school style. With Pen and Paper. Leetcode is a billion dollar mistake. Negotiate for a better hiring experience. Advocate for pair-programming and active discussion based interviews.

introduction:

priorposition:

